### ISSUE TITLE
please add Golang SDK

### ISSUE THREAD

**Issue by charsunny** [alipay/alipay-easysdk#1]
请问能添加一下golang的sdk吗？国内用golang做服务端的公司也不少，只能自己维护接口，官方有考虑支持吗？

**Comment by antopen** [comment]
感谢您的反馈，确实golang在国内发展比较迅猛。
golang的支持目前我们尚未启动，3月我们Alipay Easy SDK会优先支持php，然后再考虑支持golang。
Alipay Easy SDK 2020年最终会支持广泛的主流语言，这是我们的目标，也是广大开发者对我们期望，我们会努力的。

**Comment by charsunny** [comment]
> 感谢您的反馈，确实golang在国内发展比较迅猛。
> golang的支持目前我们尚未启动，3月我们Alipay Easy SDK会优先支持php，然后再考虑支持golang。
> Alipay Easy SDK 2020年最终会支持广泛的主流语言，这是我们的目标，也是广大开发者对我们期望，我们会努力的。

感谢 希望能尽快～

**Comment by Sakurasan** [comment]
臣复议(不然就自己造轮子

**Comment by fatindeed** [comment]
臣复议

**Comment by ccwork98** [comment]
现在还是不能支持吗，都7月了

**Comment by wongyuanrong** [comment]
8月份了，golang SDK在开发了吗

**Comment by hd10180** [comment]
请问有支持python的计划吗

**Comment by zzzmyfox** [comment]
golang目前只能自己造轮子

**Comment by tzsword** [comment]
请问能添加一下 ~~golang~~ rust 的sdk吗？国内用 ~~golang~~ rust 做服务端的公司也不少，只能自己维护接口，官方有考虑支持吗？

**Comment by drrrMikado** [comment]
12月了，还在开发吗
