### ISSUE TITLE
使用证书模式提示签名失败,公钥模式正常

### ISSUE THREAD

**Issue by tengmeicore** [alipay/alipay-easysdk#103]
<img width="732" alt="微信图片_20200724151429" src="https://user-images.githubusercontent.com/54737555/88368343-70e9b200-cdc0-11ea-9669-a3e90631413f.png">

**Comment by tengmeicore** [comment]
<img width="732" alt="微信图片_20200724151429" src="https://user-images.githubusercontent.com/54737555/88368410-9971ac00-cdc0-11ea-9a51-f4ae9bba1fc3.png">
使用公钥模式可以正常是hi用,使用证书模式报签名异常

**Comment by antopen** [comment]
请检查私钥设置是否正确，如果仍然找不到原因，建议前往https://opensupport.alipay.com/support/home.htm技术支持中心寻求人工咨询帮助。
