### ISSUE TITLE
Factory.Payment.Page().pay中return url验签问题

### ISSUE THREAD

**Issue by liangxp** [alipay/alipay-easysdk#104]
Factory.Payment.Page().pay中returnUrl中，get请求是否支持验签？
采用Factory.Payment.Common().verifyNotify不能正常验签通过！如果不设置returnUrl，用户支付后无法正常跳转。

**Comment by antopen** [comment]
verifyNotify是收到支付类异步通知时的验签方法，是验证收到的通知是否是支付宝官方发出的。
不知道你的使用场景是不是这个。
