### ISSUE TITLE
Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by ghost** [alipay/alipay-easysdk#105]
vendor/alipaysdk/easysdk/php/src/Kernel/Util/AntCertificationUtil.php at line 76

 * @return int|string
70      */
71     function hex2dec($hex)
72     {
73         $dec = 0;
74         $len = strlen($hex);
75         for ($i = 1; $i <= $len; $i++) {
76             $dec = bcadd($dec, bcmul(strval(hexdec($hex[$i - 1])), bcpow('16', strval($len - $i))));
77         }
78         return $dec;
79     }

**Comment by tcyfree** [comment]
这个问题解决了嘛，我也遇到了
