### ISSUE TITLE
从2.0.0版本开始，kotlin项目中使用会报警告

### ISSUE THREAD

**Issue by JackyLeeCS** [alipay/alipay-easysdk#108]
[WARNING] Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath

**Comment by JackyLeeCS** [comment]
为什么会把kotlin打包到sdk中呢

**Comment by antopen** [comment]
SDK中使用了okHttp这个网络库，该库中依赖了kotlin。
