### ISSUE TITLE
Factory.Payment.Common().VerifyNotify 验签遭遇异常

### ISSUE THREAD

**Issue by rose-daniel** [alipay/alipay-easysdk#111]
// 使用Dictionary保存参数
            Dictionary<string, string> resData = new Dictionary<string, string>();

            IFormCollection forms = Request.Form;
            string[] requestItem = forms.Keys.ToArray();

            for (int i = 0; i < requestItem.Length; i++)
            {
                resData.Add(requestItem[i], Request.Form[requestItem[i]]);
            }

Factory.Payment.Common().VerifyNotify(resData) 

验签遭遇异常, publicKey= reason=PEM格式公钥不可为空

如题 IsCertMode 为真 为什么公钥为空呢？
![微信图片_20200803170602](https://user-images.githubusercontent.com/40789760/89166141-292b0d80-d5ac-11ea-8a96-808851c4cb4f.png)

**Comment by antopen** [comment]
是不是没有调用Factory.setOptions对SDK进行初始化。

**Comment by rose-daniel** [comment]
Factory.setOptions 已经初始化 不是这个问题呀

**Comment by antopen** [comment]
证书模式下，支付宝公钥是从证书中提取的，
异步验签情况下，直接从setOptions缓存的证书公钥中提取出公钥，所以无需指定额外信息，源码你箭头所指出空字符串是正常的。

可以再检查下是不是setOptions时，支付宝公钥证书没有指定对。

**Comment by rose-daniel** [comment]
Alipay.EasySDK.Kernel 下 CertEnvironment 类 GetAlipayPublicKey 方法 返回值
return CachedAlipayPublicKey.Values.GetEnumerator().Current;  
改为
return CachedAlipayPublicKey.Values.FirstOrDefault();

**Comment by antopen** [comment]
2.0.1版本中已修复此问题。
