### ISSUE TITLE
支付退款异常

### ISSUE THREAD

**Issue by huanghao-db** [alipay/alipay-easysdk#115]
Factory.Payment.Common()
                .asyncNotify("http://www.baidu.com")
                .optional("out_request_no",outRequestNo)
                .refund(outTradeNo, refundAmount);

Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: okhttp3.Headers.iterator()Ljava/util/Iterator;

请问这是什么原因

**Comment by antopen** [comment]
可能是由于参数设置错误，导致网关返回了预期外格式的响应。
setOptions中设置的参数可以发下么？（密钥相关的记得脱敏）

**Comment by huanghao-db** [comment]
Config config = new Config();
        config.protocol = aliPayProperties.getProtocol();
        config.gatewayHost = aliPayProperties.getGatewayHost();
        config.appId = aliPayProperties.getAppId();
        config.signType = aliPayProperties.getSignType();
        config.merchantPrivateKey = aliPayProperties.getMerchantPrivateKey();
        config.merchantCertPath = aliPayProperties.getMerchantCertPath();
        config.alipayCertPath = aliPayProperties.getAlipayCertPath();
        config.alipayRootCertPath = aliPayProperties.getAlipayRootCertPath();
        config.encryptKey = aliPayProperties.getEncryptKey();
        Factory.setOptions(config);

**Comment by povoss** [comment]
@紫青 大神，真的是和tencentcloud-sdk-java冲突了，它用的2.5的okhttp版本,而支付宝用的4.4.1.

**Comment by Ami-Kawashima** [comment]
请问下有进展么? 我今天也遇到了这个错误

**Comment by FngSe** [comment]
@povoss 求解决的办法吗

**Comment by fantasyado** [comment]
@FngSe  @Ami-Kawashima  解决了，在pom里添加
`    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>3.8.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>`

详见： https://stackoverflow.com/questions/7175398/maven-dependency-resolution-conflicted
