### ISSUE TITLE
支付宝身份认证问题，参数3，根据官方文档传入报错

### ISSUE THREAD

**Issue by dadjdka** [alipay/alipay-easysdk#119]
Argument 3 passed to Alipay\EasySDK\Member\Identification\Client::init() must be an instance of Alipay\EasySDK\Member\Identification\Models\IdentityParam, string given, called

**Comment by antopen** [comment]
请问使用的是什么语言什么版本的SDK？

**Comment by soul-key** [comment]
因为第三，四个参数为类，不能直接传字符串，要如下如使用（目前自己用的，没问题）：
` //1. 设置参数（全局只需设置一次）
        Factory::setOptions(AlipayUser::getOptions());
        $param = ["identityType" => "CERT_INFO", "certType" => "IDENTITY_CARD", "certName" => "王五", "certNo" => "1306214455412"];
        $meConfig=['returnUrl' => "/api/user/zfbverify"];
        $orderNo=date("YmdHis") . rand(111111, 999999);
        //出现"40004 未知错误"，原因是订单号太短,当订单号长度够了但重复时，将提示"40004 参数异常"
        $res = Factory::member()->identification()->init($orderNo, "FACE", new IdentityParam($param), new MerchantConfig($meConfig));
        $body = json_decode($res->httpBody, true);
        var_dump($res->httpBody);
        die;`
