### ISSUE TITLE
easySDK2.0【获取用户信息】时报：wordwrap() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by kenny534** [alipay/alipay-easysdk#120]
根据文档提示，已经完成了用户点击同意授权这个界面，但当用户点了同意之后，回调地址接收到了如下信息
array:7 [▼
  "state" => "b102a787fc6f99384e9f54fd01860a6c"
  "app_id" => "202********5339"
  "source" => "alipay_wallet"
  "userOutputs" => "auth_user"
  "scope" => "auth_user"
  "alipay_token" => ""
  "auth_code" => "91b5uyuu38876765927f32f442d7ZX92"
]
使用auth_code,获取用户信息时报错：wordwrap() expects parameter 1 to be string, array given

回调方法的具体代码如下：

        $params = $this->request->param(); //获取支付宝推送数据
        
        echo gettype($params['auth_code']); //打印auth_code的数据类型，结果为string

        echo json_encode($params); //测试转json是否成功(成功)

         \Alipay\EasySDK\Kernel\Factory::setOptions($this->getOptions());

        try{
            $result = \Alipay\EasySDK\Kernel\Factory::base()->OAuth()->getToken($params['auth_code']); //在这里就报错了，直接进入catch 分支，此处如果直接写死为"91b5uyuu38876765927f32f442d7ZX92"（auth_code）也报同样错误

            if (!empty($result->code) && $result->code==10000){
                echo '调用成功'.PHP_EOL;
            }
            else{
                echo '调用失败，原因：'.$result->msg.",".$result->sub_msg.PHP_EOL;
            }
        }
        catch (\Exception $e){
            echo '调用失败'.$e->getMessage().PHP_EOL;
        }
        dump($params); //前文看到的array7.......
        烦请协助解决此问题,谢谢！

**Comment by kenny534** [comment]
\Alipay\EasySDK\Kernel\Factory::setOptions($this->getOptions());
这行代码中的getOptions()方法里有个bug:（1楼没有贴出来）
按照官方建议，从文件中读取私钥，使用了file()函数，但忘记了该函数返回数组类型，私钥的内容应该是这样获取：
$private_key = file('你的私钥存放目录/私钥文件名称')
$options->merchantPrivateKey = $private_key[0]; /** file()读取到数组中，取第一行 */
另外一个解决办法，就是官方不推荐的：直接把私钥内容赋值给merchantPrivateKey:
$options->merchantPrivateKey = 'MIIEvg......';

解决上述问题后：又出现了如下报错：
调用失败Undefined property: **Alipay\EasySDK\Base\OAuth\Models\AlipaySystemOauthTokenResponse::$sub_msg**
希望高手进来指点，谢谢！

**Comment by antopen** [comment]
已经钉钉联系解决
