### ISSUE TITLE
部分功能在新的sdk中无法使用

### ISSUE THREAD

**Issue by twelife** [alipay/alipay-easysdk#121]
语言版本：`php`
接口：`alipay.fund.auth.order.app.freeze(线上资金授权冻结接口)`

使用通用接口处理，接口一直返回系统繁忙
解决方案是仍然需要使用老版本的`sdk`才可以使用，跟客服有确认过，新版本的`easysdk`无法使用

**希望可以新老版本问题处理同步**

**Comment by antopen** [comment]
这个接口应该是可以用通用接口调用的。是不是参数设置上有问题，有些参数错误也可能导致系统繁忙。
你这边方便贴一下你的调用代码么。

**Comment by ezhiyu126** [comment]
接口：alipay.fund.auth.order.app.freeze(线上资金授权冻结接口) 在easysdk 还没有支持sdkExecute 这个特殊的接口 如果使用了execute 就会报这个错了

**Comment by hopaheal** [comment]
新版支持吗？你们咋解决的

**Comment by etoup** [comment]
请问有解决方案？
