### ISSUE TITLE
c# 调用验签接口报错，提示“PEM格式公钥不可为空”

### ISSUE THREAD

**Issue by yw2705** [alipay/alipay-easysdk#124]
调用接口Factory.Payment.Common().VerifyNotify()进行验签的时候，会报错“PEM格式公钥不可为空”
再三检查过，设置的时候有传入支付宝公钥证书的地址

后来下载git上的源码引入进行调试后，发现是Alipay.EasySDK.Kernel下面的GetAlipayPublicKey方法有问题，
`return CachedAlipayPublicKey.Values.GetEnumerator().Current;`
这里return的时候CachedAlipayPublicKey.Values中是有值的，但是GetEnumerator()后，返回的是null，导致SDK报错“PEM格式公钥不可为空”

```
        public string GetAlipayPublicKey(string sn)
        {
            //如果没有指定sn，则默认取缓存中的第一个值
            if (string.IsNullOrEmpty(sn))
            {
                return CachedAlipayPublicKey.Values.GetEnumerator().Current;
            }
            ...
        }
```

**Comment by antopen** [comment]
感谢反馈，我们会尽快修复此问题。

**Comment by antopen** [comment]
2.0.1版本已修复此问题。
