### ISSUE TITLE
系统中有多个支付宝API账号如何处理

### ISSUE THREAD

**Issue by vcharfred** [alipay/alipay-easysdk#128]
请问 系统中对应不同的业务使用不同的支付宝账号，应该如何来初始化 应用私钥等 这些配置信息？目前只有全局设置或者是根据需要初始化不同的配置请求客户端

**Comment by sunshixiong789** [comment]
同求

**Comment by WunHwanTseng** [comment]
加一

**Comment by 1107115073** [comment]
同求

**Comment by sunshixiong789** [comment]
我用一种方式解决了；

`/**
 * 支付宝支付配置
 *
 * @author sunshixiong（1285913468@qq.com）
 * @date 2020/8/3-15:26
 */
@Component
@RequiredArgsConstructor
public class AliplayConfig {

  public static Map<String, Payment> paymentMap = new HashMap<>();
  private final AlipayProperties properties;

  /**
   * 配置支付宝账号信息
   *
   * @throws IOException 从读取公钥或者私钥错误
   */
  @PostConstruct
  public void factoryInit() throws IOException {
    ArrayList<AlipayInfo> info = properties.getInfo();
    for (AlipayInfo item : info) {
      Config config = new Config();
      if (item.getEnable()) {
        config.protocol = item.getProtocol();
        config.gatewayHost = item.getGatewayHost();
        config.signType = item.getSignType();
        config.appId = item.getAppId();
        config.merchantPrivateKey = getFileString(item.getMerchantPrivateKeyPath());
        if (item.getKeyPattern()) {
          config.merchantCertPath = item.getMerchantCertPath();
          config.alipayCertPath = item.getAlipayCertPath();
          config.alipayRootCertPath = item.getAlipayRootCertPath();
        } else {
          config.alipayPublicKey = getFileString(item.getAlipayPublicKeyPath());
        }
        paymentMap.put(item.getPayUser(), new Payment(config));
      }
    }
  }
}`
AlipayFactory  类(从Factory类中提取的)
`package com.mskysoft.unifiedpaymentplatform.utils;

import com.alipay.easysdk.kernel.AlipayConstants;
import com.alipay.easysdk.kernel.Client;
import com.alipay.easysdk.kernel.Config;
import com.alipay.easysdk.kernel.Context;
import com.alipay.easysdk.kms.aliyun.AliyunKMSClient;
import com.alipay.easysdk.kms.aliyun.AliyunKMSSigner;
import com.aliyun.tea.TeaModel;

/**
 * 阿里支付
 *
 * @author sunshixiong（1285913468@qq.com）
 * @date 2020/8/24-15:23
 */
public class AlipayFactory {
  public static final String SDK_VERSION = "alipay-easysdk-java-2.0.0";

  /**
   * 将一些初始化耗时较多的信息缓存在上下文中
   */
  private Context context;

  /**
   * 设置客户端参数，只需设置一次，即可反复使用各种场景下的API Client
   *
   * @param options 客户端参数对象
   */
  public AlipayFactory(Config options) {
    try {
      context = new Context(options, SDK_VERSION);

      if (AlipayConstants.AliyunKMS.equals(context.getConfig(AlipayConstants.SIGN_PROVIDER_CONFIG_KEY))) {
        context.setSigner(new AliyunKMSSigner(new AliyunKMSClient(TeaModel.buildMap(options))));
      }

    } catch (Exception e) {
      throw new RuntimeException(e.getMessage(), e);
    }
  }


  /**
   * 基础能力相关
   */
  public class Base {
    /**
     * 获取图片相关API Client
     *
     * @return 图片相关API Client
     */
    public com.alipay.easysdk.base.image.Client Image() throws Exception {
      return new com.alipay.easysdk.base.image.Client(new Client(context));
    }

    /**
     * 获取视频相关API Client
     *
     * @return 视频相关API Client
     */
    public com.alipay.easysdk.base.video.Client Video() throws Exception {
      return new com.alipay.easysdk.base.video.Client(new Client(context));
    }

    /**
     * 获取OAuth认证相关API Client
     *
     * @return OAuth认证相关API Client
     */
    public com.alipay.easysdk.base.oauth.Client OAuth() throws Exception {
      return new com.alipay.easysdk.base.oauth.Client(new Client(context));
    }

    /**
     * 获取小程序二维码相关API Client
     *
     * @return 小程序二维码相关API Client
     */
    public com.alipay.easysdk.base.qrcode.Client Qrcode() throws Exception {
      return new com.alipay.easysdk.base.qrcode.Client(new Client(context));
    }
  }

  /**
   * 营销能力相关
   */
  public class Marketing {
    /**
     * 获取生活号相关API Client
     *
     * @return 生活号相关API Client
     */
    public com.alipay.easysdk.marketing.openlife.Client OpenLife() throws Exception {
      return new com.alipay.easysdk.marketing.openlife.Client(new Client(context));
    }

    /**
     * 获取支付宝卡包相关API Client
     *
     * @return 支付宝卡包相关API Client
     */
    public com.alipay.easysdk.marketing.pass.Client Pass() throws Exception {
      return new com.alipay.easysdk.marketing.pass.Client(new Client(context));
    }

    /**
     * 获取小程序模板消息相关API Client
     *
     * @return 小程序模板消息相关API Client
     */
    public com.alipay.easysdk.marketing.templatemessage.Client TemplateMessage() throws Exception {
      return new com.alipay.easysdk.marketing.templatemessage.Client(new Client(context));
    }
  }

  /**
   * 会员能力相关
   */
  public class Member {
    /**
     * 获取支付宝身份认证相关API Client
     *
     * @return 支付宝身份认证相关API Client
     */
    public com.alipay.easysdk.member.identification.Client Identification() throws Exception {
      return new com.alipay.easysdk.member.identification.Client(new Client(context));
    }
  }

  /**
   * 安全能力相关
   */
  public class Security {
    /**
     * 获取文本风险识别相关API Client
     *
     * @return 文本风险识别相关API Client
     */
    public com.alipay.easysdk.security.textrisk.Client TextRisk() throws Exception {
      return new com.alipay.easysdk.security.textrisk.Client(new Client(context));
    }
  }

  /**
   * 辅助工具
   */
  public class Util {
    /**
     * 获取OpenAPI通用接口，可通过自行拼装参数，调用几乎所有OpenAPI
     *
     * @return OpenAPI通用接口
     */
    public com.alipay.easysdk.util.generic.Client Generic() throws Exception {
      return new com.alipay.easysdk.util.generic.Client(new Client(context));
    }

    /**
     * 获取AES128加解密相关API Client，常用于会员手机号的解密
     *
     * @return AES128加解密相关API Client
     */
    public com.alipay.easysdk.util.aes.Client AES() throws Exception {
      return new com.alipay.easysdk.util.aes.Client(new Client(context));
    }
  }
}
`

**Comment by sunshixiong789** [comment]
我用一种方式实现了，还是很优雅的；两个类搞定：

`@Component
@RequiredArgsConstructor
public class AliplayConfig {

  public static Map<String, Payment> paymentMap = new HashMap<>();
  private final AlipayProperties properties;

  @PostConstruct
  public void factoryInit() throws IOException {
    ArrayList<AlipayInfo> info = properties.getInfo();
    for (AlipayInfo item : info) {
      Config config = new Config();
      if (item.getEnable()) {
        config.protocol = item.getProtocol();
        config.gatewayHost = item.getGatewayHost();
        config.signType = item.getSignType();
        config.appId = item.getAppId();
        config.merchantPrivateKey = getFileString(item.getMerchantPrivateKeyPath());
        if (item.getKeyPattern()) {
          config.merchantCertPath = item.getMerchantCertPath();
          config.alipayCertPath = item.getAlipayCertPath();
          config.alipayRootCertPath = item.getAlipayRootCertPath();
        } else {
          config.alipayPublicKey = getFileString(item.getAlipayPublicKeyPath());
        }
        paymentMap.put(item.getPayUser(), new Payment(config));
      }
    }
  }
}`

- 

- ### 另一个：

`public class Payment {
  /**
   * 将一些初始化耗时较多的信息缓存在上下文中
   */
  private Context context;
  public static final String SDK_VERSION = "alipay-easysdk-java-2.0.0";

  public Payment(Config options) {
    try {
      context = new Context(options, SDK_VERSION);

      if (AlipayConstants.AliyunKMS.equals(context.getConfig(AlipayConstants.SIGN_PROVIDER_CONFIG_KEY))) {
        context.setSigner(new AliyunKMSSigner(new AliyunKMSClient(TeaModel.buildMap(options))));
      }

    } catch (Exception e) {
      throw new RuntimeException(e.getMessage(), e);
    }
  }

  /**
   * 获取支付通用API Client
   *
   * @return 支付通用API Client
   */
  public com.alipay.easysdk.payment.common.Client Common() throws Exception {
    return new com.alipay.easysdk.payment.common.Client(new Client(context));
  }

  /**
   * 获取花呗相关API Client
   *
   * @return 花呗相关API Client
   */
  public com.alipay.easysdk.payment.huabei.Client Huabei() throws Exception {
    return new com.alipay.easysdk.payment.huabei.Client(new Client(context));
  }

  /**
   * 获取当面付相关API Client
   *
   * @return 当面付相关API Client
   */
  public com.alipay.easysdk.payment.facetoface.Client FaceToFace() throws Exception {
    return new com.alipay.easysdk.payment.facetoface.Client(new Client(context));
  }

  /**
   * 获取电脑网站支付相关API Client
   *
   * @return 电脑网站支付相关API Client
   */
  public com.alipay.easysdk.payment.page.Client Page() throws Exception {
    return new com.alipay.easysdk.payment.page.Client(new Client(context));
  }

  /**
   * 获取手机网站支付相关API Client
   *
   * @return 手机网站支付相关API Client
   */
  public com.alipay.easysdk.payment.wap.Client Wap() throws Exception {
    return new com.alipay.easysdk.payment.wap.Client(new Client(context));
  }

  /**
   * 获取手机APP支付相关API Client
   *
   * @return 手机APP支付相关API Client
   */
  public com.alipay.easysdk.payment.app.Client App() throws Exception {
    return new com.alipay.easysdk.payment.app.Client(new Client(context));
  }
}
`

**Comment by JHeLiu** [comment]
@sunshixiong789  这个只能保证稍微就几个，如果 配置是动态切换的何解，比如多商户那种

**Comment by KXinghui** [comment]
可以使用 MultipleFactory
