### ISSUE TITLE
这个新版支持1.7以上的版本，但是1.7无法运行

### ISSUE THREAD

**Issue by simpleSOA** [alipay/alipay-easysdk#130]
我看了maven仓库的jar，MANIFEST.MF这个文件里面的信息
Created-By: Apache Maven
Built-By: zhongyu
Build-Jdk: 1.8.0_241
这个jar是1.8编译出来的，如果项目是1.7的版本，就无法运行，会出现Unsupported major.minor version 52.0
最新的包引用了com.aliyun.tea:1.0.3这个版本，这个版本我看pom文件编译是1.8

**Comment by antopen** [comment]
不好意思，最新版本目前推荐使用JDK1.8及其以上版本，我们调整下相关说明。
