### ISSUE TITLE
转账到支付宝账户

### ISSUE THREAD

**Issue by li-guojiang** [alipay/alipay-easysdk#131]
是否有 用于向指定支付宝账户转账（alipay.fund.trans.uni.transfer） 的功能？

**Comment by antopen** [comment]
可以用Factory.Util.Generic.execute通用接口覆盖。

**Comment by zhangchenglin** [comment]
> 可以用Factory.Util.Generic.execute通用接口覆盖。

https://github.com/alipay/alipay-easysdk/blob/master/APIDoc.md#%E9%80%9A%E7%94%A8%E6%8E%A5%E5%8F%A3-generic

是这个吧
