### ISSUE TITLE
Generic没有提供图片参数

### ISSUE THREAD

**Issue by woochanglin** [alipay/alipay-easysdk#132]
EasySDK未正式提供的API，可以通过Generic进行调用，但是没有提供图片参数，比如：alipay.open.agent.facetoface.sign中的营业执照照片，店面照片等。

**Comment by antopen** [comment]
感谢反馈，目前确实不支持，后续计划推出支持文件上传的 Generic方法。

**Comment by woochanglin** [comment]
老SDK体积太大，很多API用不到，也打在了JAR包中，老SDK可以按业务分包。如果切换到EasySDK，那肯定是要整体切换，如果不能提供文件参数，对于很多用户来说，是无法切换的。建议尽快增加文件参数。

**Comment by antopen** [comment]
最新版已经支持图片类型
