### ISSUE TITLE
2.0.2版本

### ISSUE THREAD

**Issue by gyli2016** [alipay/alipay-easysdk#134]
Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.Headers.iterator()Ljava/util/Iterator;
	at com.aliyun.tea.TeaResponse.<init>(TeaResponse.java:30)
	at com.aliyun.tea.Tea.doAction(Tea.java:63)
	at com.alipay.easysdk.payment.common.Client.create(Client.java:71)

**Comment by antopen** [comment]
https://github.com/alipay/alipay-easysdk/issues/135

跟这个问题应该是一样的原因。与你的项目中原来依赖的okhttp的版本冲突了。

**Comment by hebiao89757** [comment]
> [＃135](https://github.com/alipay/alipay-easysdk/issues/135)
> 
> 跟这个问题应该是一样的原因。与你的项目中原来依赖的okhttp的版本冲突了。

解决版本冲突还是不行，能帮忙看看什么原因吗

![image](https://user-images.githubusercontent.com/29088269/92691225-d4ca3900-f374-11ea-9b5e-64e741c3c93f.png)

**Comment by gyli2016** [comment]
> [＃135](https://github.com/alipay/alipay-easysdk/issues/135)
> 
> 跟这个问题应该是一样的原因。与你的项目中原来依赖的okhttp的版本冲突了。
我没有依赖okhttp这个包，切换成 2.0.0 版本就没这个问题了

**Comment by gyli2016** [comment]
> > [＃135](https://github.com/alipay/alipay-easysdk/issues/135)
> > 跟这个问题应该是一样的原因。与你的项目中原来依赖的okhttp的版本冲突了。
> 
> 解决版本冲突还是不行，能帮忙看看什么原因吗
> 
> ![图片](https://user-images.githubusercontent.com/29088269/92691225-d4ca3900-f374-11ea-9b5e-64e741c3c93f.png)

我切换成  2.0.0 版本就没这个问题了 ，你可以试试
