### ISSUE TITLE
easysdk依赖了okhttp吗？

### ISSUE THREAD

**Issue by yizhitangtongxue** [alipay/alipay-easysdk#135]

**Comment by yizhitangtongxue** [comment]
需要手动添加4.8.1的okhttp依赖
运行程序时，如果控制台开头报kotlin的waring，需要将spring更新到2.3.3或者更新spring-core到5.2.8

**Comment by antopen** [comment]
是的，依赖了okhttp。

**Comment by hebiao89757** [comment]
查询支付 报错的问题你们解决了吗，搞一天了

**Comment by hebiao89757** [comment]
> 是的，依赖了okhttp。

查询支付报错的问题你们解决了吗，搞一天了

**Comment by jyl741230** [comment]
我升级了okhttp 到4.8.1 ， spring -core 也升级到5.28了，还是报错

**Comment by antopen** [comment]
大家可以试试2.1.0版本，降低了对OkHttp新特性的依赖。
