### ISSUE TITLE
查询支付情况报错

### ISSUE THREAD

**Issue by hbyexplore** [alipay/alipay-easysdk#136]
AlipayTradeQueryResponse query = Factory.Payment.Common().query("123456");

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: okhttp3.Headers.iterator()Ljava/util/Iterator;
Caused by: java.lang.NoSuchMethodError: okhttp3.Headers.iterator()Ljava/util/Iterator;

why？？

**Comment by antopen** [comment]
https://github.com/alipay/alipay-easysdk/issues/135
参考这个问题，尝试升级下okhttp的版本。

**Comment by hbyexplore** [comment]
的确,升级okhttp版本之后好了
