### ISSUE TITLE
签名算法能支持更安全的SHA256WithRSA/PSS吗？

### ISSUE THREAD

**Issue by garyingithub** [alipay/alipay-easysdk#139]
公司安全规则要求使用SHA256WithRSA/PSS进行签名。能提供吗支持？

**Comment by antopen** [comment]
参数设置signType=RSA2（默认也是这个值）时，是采用的SHA256WithRSA签名算。

**Comment by garyingithub** [comment]
但是没有使用PSS填充

**Comment by garyingithub** [comment]
> 参数设置signType=RSA2（默认也是这个值）时，是采用的SHA256WithRSA签名算法。

但是没有使用PSS填充

**Comment by antopen** [comment]
PSS填充暂时无法支持。
