### ISSUE TITLE
easysdk与银联支付冲突问题

### ISSUE THREAD

**Issue by hemingchao** [alipay/alipay-easysdk#140]
你好，近期接入贵公司的支付宝支付，但出现了与银联支付冲突的情况，具体报错情况如下。com/alipay/sdk/alipay-easysdk/2.0.1/alipay-easysdk-2.0.1.jar has unsigned entries - com/alipay/easysdk/kms/aliyun/AliyunRpcClient.class     自己比较愚笨暂时没找到解决方案，烦请帮忙给指导下。非常感谢！

**Comment by antopen** [comment]
是怎么确定跟银联支付冲突的？ 在一个普通项目中引用会不会也报这个错？
