### ISSUE TITLE
.net core 2.0.0 版本巨大BUG，作为大公司不能严谨一点么

### ISSUE THREAD

**Issue by lld1995** [alipay/alipay-easysdk#142]
.net core 2.0.0 版本居然验签报错PEM PUBLIC KEY 为空，而且遇到这种问题，除了拉源码，这种封装模式完全不留任何调试的余地。升级到2.0.1 居然就好了，真是醉了，浪费1个多小时

**Comment by antopen** [comment]
感谢您的反馈，您遇到的问题确实是在2.0.1版本中修复的，十分抱歉给您带来的困扰。我们已将2.0.0版本从NuGet中隐藏，以避免出现再出现类似问题。后续我们会更加注重产品质量的管控。
