### ISSUE TITLE
SDK 创建订单必传buyer_id 但是H5里面如何获取这个用户id呢？

### ISSUE THREAD

**Issue by ytrlmy521** [alipay/alipay-easysdk#147]
使用了新版的DeasySDK 创建订单的时候，需要传buyerId ，但是在H5中需要先获取到buyerId吗 ？？，通过静默授权的方式获取，然后在调用Payment.Common().create()接口。

还请大神明示。

**Comment by antopen** [comment]
需要的，先通过用户授权拿到买方的userId作为buyerId.
