### ISSUE TITLE
调用异常

### ISSUE THREAD

**Issue by uhyintl** [alipay/alipay-easysdk#156]
复制例子写的调用出现
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by uhyintl** [comment]
使用的是sdk版本是2.1.0 之后切换2.0.0和2.0.1 都是相同报错

**Comment by Wang-Hai-Cheng** [comment]
> 复制例子写的调用出现
> java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

查看网关是否正确，正确配置是这样的地址        config.gatewayHost = "openapi.alipay.com";//阿里网关地址
