### ISSUE TITLE
Factory context 线程安全吗

### ISSUE THREAD

**Issue by MroZ11** [alipay/alipay-easysdk#158]
程序需要同时给多个支付方使用，多次使用Factory.setOptions() 并发时，会不会生成错误的订单？

**Comment by antopen** [comment]
如果有并发是有可能的， 串行是没问题的。

**Comment by antopen** [comment]
https://github.com/alipay/alipay-easysdk/issues/149  
可以参考下历史类似的讨论。

**Comment by MroZ11** [comment]
明白了 感谢
