### ISSUE TITLE
好垃圾的SDK,丢阿里的人

### ISSUE THREAD

**Issue by LeftH0ok** [alipay/alipay-easysdk#161]
D:\xampp\htdocs\qianmei>composer require alipaysdk/easysdk:^2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 0 updates, 0 removals
  - Installing xin/helper (1.0.0): Cloning 02a58132da

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]
  Failed to clone https://gitee.com/liuxiaojinla/php-helper, git was not found, check that it is installed and in you
  r PATH env.

  'git' is not recognized as an internal or external command,
  operable program or batch file.

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by antopen** [comment]
亲，请检查下您是否没有安装git。
![image](https://user-images.githubusercontent.com/34638345/96106037-49ad0780-0f0d-11eb-9eaf-8ab7e336f503.png)
