### ISSUE TITLE
PHP verifyNotify error

### ISSUE THREAD

**Issue by dongbin666666** [alipay/alipay-easysdk#163]
Factory::payment()->common()->verifyNotify($post) 验签不通过，和支付是同样的配置，证书模式

**Comment by dongbin666666** [comment]
已解决：需要在验签之前需要对参数做下处理，需要将&quot;替换成"：
        $params = $request->param();//tp5的request对象直接获取参数
        //替换字符-解决验签不通过的问题：验签前加一句代码
        $params = json_decode(str_replace('&quot;', '\"', json_encode($params, JSON_UNESCAPED_UNICODE)), true);

**Comment by dongbin666666** [comment]
$params = $request->param();
             //替换字符-解决验签不通过的问题
             $params = json_decode(str_replace('&quot;', '\"', json_encode($params, JSON_UNESCAPED_UNICODE)), true);
             //验签
            $verify_result = Factory::payment()->common()->verifyNotify($params);
            //记录一下请求参数
            log_file(json_encode($params, JSON_UNESCAPED_UNICODE), 'alipay_notify', 'alipay');
            //记录验签结果
            log_file(['verify_result'=>$verify_result], 'alipay_notify', 'alipay');
            
            if (!$verify_result) exit('验签失败');

            //处理你的逻辑

**Comment by FeiLiao-9** [comment]
我按照你这样还是验签不通过，用老版本的支付是可以的

**Comment by FeiLiao-9** [comment]
我使用的TP6框架，是在路由上添加了参数导致的。验证签名的时候把多余参数删除掉就好了
