### ISSUE TITLE
SDK内部报错

### ISSUE THREAD

**Issue by Developer-echo** [alipay/alipay-easysdk#165]
.NET Framework4.7.2
---------------------------------------
 var result = await Factory.Util.Generic().ExecuteAsync(method, textParams, bizParams);
var result = await Factory.Payment.Common().RefundAsync(out_trader_no, money.ToString());
var result = Factory.Payment.Common().Query(out_trader_no);
-----------------------------------------
相同错误
错误信息：
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by antopen** [comment]
是不是options中设置的参数格式有问题。
