### ISSUE TITLE
如果我有多个支付宝账号要使用，该怎么做

### ISSUE THREAD

**Issue by JHeLiu** [alipay/alipay-easysdk#167]
如果我有多个支付宝账号要使用，该怎么做

```
 // 1. 设置参数（全局只需设置一次）
  Factory.SetOptions(GetConfig());
```
SDK 的文档告诉我们只需要设置一次，如果对于多个支付宝账号，动态切换 我们应该怎么做？

**Comment by sovwcwsfm** [comment]
同问

**Comment by sovwcwsfm** [comment]
使用2.2.0版本，参考这个测试用例使用：https://github.com/alipay/alipay-easysdk/blob/master/java/src/test/java/com/alipay/easysdk/multipleFactory/MultipleFactoryTest.java
