### ISSUE TITLE
配置证书路径，出现路径为空情况

### ISSUE THREAD

**Issue by p-jiangxiaozhou** [alipay/alipay-easysdk#177]
![image](https://user-images.githubusercontent.com/73947337/100080642-09806380-2e81-11eb-9d41-9b09ab53f0ae.png)

**Comment by p-jiangxiaozhou** [comment]
![image](https://user-images.githubusercontent.com/73947337/100080814-3c2a5c00-2e81-11eb-9829-3f0b706f4387.png)

**Comment by p-jiangxiaozhou** [comment]
![image](https://user-images.githubusercontent.com/73947337/100080956-6ed45480-2e81-11eb-87ad-e0c7d403eaf8.png)

**Comment by antopen** [comment]
使用时路径证书参数和应用私钥参数配置错误
