### ISSUE TITLE
php封装的过于私密，无法从外部直接调起加签名的方法

### ISSUE THREAD

**Issue by ruoge3s** [alipay/alipay-easysdk#18]
php的sdk封装的一次到位，使用该sdk的开发者就无法随意调取任意环节进行自行构造请求的目的
比如我只需要一个签名的类，其他功能都不用，就无法直接只调用签名相关的功能
基础的设计应该是 
http请求功能，加解密相关的功能，其他底层的功能..；
基于基础功能的业务接口请求功能，针对业务功能结果的处理功能(开发者在调用这一层的时候可以自己注入http请求client)

**Comment by antopen** [comment]
感谢您的反馈，我们下一版本迭代就会支持这类需求

**Comment by antopen** [comment]
最先版已经支持异步验签功能，相见readme，欢迎使用
