### ISSUE TITLE
支付宝预授权什么时候集成进去-php

### ISSUE THREAD

**Issue by 13sai** [alipay/alipay-easysdk#189]
支付宝预授权什么时候集成进去，暂时只能使用php-sdk中那种require的方式吗？

`require_once 'AopEncrypt.php';
require_once 'EncryptParseItem.php';
require_once 'EncryptResponseData.php';
require_once 'SignData.php';
class AopClient
{...`

**Comment by antopen** [comment]
可以通过Util-》Generic-》execute 通用接口调用
