### ISSUE TITLE
alipay.fund.trans.uni.transfer(单笔转账接口) PHP版本还不支持吗？

### ISSUE THREAD

**Issue by kideny** [alipay/alipay-easysdk#211]
这个能否尽快支持一下呢？

**Comment by antopen** [comment]
可以通过Util-》Generic-》execute 通用接口调用

**Comment by kideny** [comment]
多谢提醒！！！

**Comment by kideny** [comment]
I love you ！！！

**Comment by kideny** [comment]
使用$result = $factory::util()->generic()->execute("alipay.fund.trans.uni.transfer", $textParams, $bizParams);
调试成功了！说明一下，免得其他兄弟再问。

**Comment by aogg** [comment]
\Alipay\EasySDK\Kernel\Factory::util()->generic()->execute('alipay.fund.trans.uni.transfer',  $textParams, $bizParams);
