### ISSUE TITLE
怎么设置notify_url?

### ISSUE THREAD

**Issue by ruomia** [alipay/alipay-easysdk#22]
使用时, 没有找到设置回调地址的地方, 在AopClict中, 可以通过`$request->setNotifyUrl("商户自己的notify_url地址");`进行设置, 是easysdk不需要设置吗

**Comment by antopen** [comment]
notify_url不是必选项，但是介于大部分开发者都有接收异步回调信息的需求，下周新版本中会支持notify_url的设置。

**Comment by ruomia** [comment]
好的, 谢谢回复

**Comment by LisenH** [comment]
> notify_url不是必选项，但是介于大部分开发者都有接收异步回调信息的需求，下周新版本中会支持notify_url的设置。

哎，我还是用旧版的sdk吧，等esay-sdk完全完善了再用。可惜了composer

**Comment by antopen** [comment]
easysdk 1.2.0版本后已经支持异步回调地址设置，具体使用办法见readme，欢迎使用
