### ISSUE TITLE
多开放平台账号

### ISSUE THREAD

**Issue by haoyong** [alipay/alipay-easysdk#25]
如果使用多个开放平台账号，那么使用不同的app_id时是不是先调用Factory.setOptions(getOptions())进行参数设置？
使用原有的Alipay SDK时，可以把不同app_id的AlipayClient缓存起来，下次使用从缓存中获取。easysdk有什么好的方法吗？

**Comment by antopen** [comment]
Factory.setOptions(getOptions())每次会执行一定的初始化操作（比如解析证书序列号之类的），会有一定的性能开销，只有切换频率不是特别高，比如10秒以上才切换一次，那可以每次切换前调用Factory.setOptions切换账号，否则不推荐这么做，因为可能有性能风险。

另外一种思路就是不使用Easy SDK自带的Factory单例，可以自己初始化并缓存各类API Client，比如com.alipay.easysdk.base.image.Client、com.alipay.easysdk.base.video.Client等。
可以查看Factory源码借鉴初始化并缓存Clinet的方法。

**Comment by haoyong** [comment]
好的，感谢。
