### ISSUE TITLE
.net的nuget包需要清理无用的东西

### ISSUE THREAD

**Issue by copyliu** [alipay/alipay-easysdk#26]
请不要将除了[`AlipaySDKNet.Standard.dll`](https://github.com/alipay/alipay-sdk-net-all/issues/9) 和 `AlipayEasySDK.dll`之外的东西打包进nuget里...除了造成依赖问题之外毫无用处, 请将需要用到的依赖填进nuspec的dependencies段.

具体的话如果是指向.net 4.6(不是core)的项目一旦从nuget安装AlipayEasySDK, 整个项目的系统库引用会被替换成AlipayEasySDK自带的一堆DLL, 造成各种各样的依赖错误和版本错误问题

**Comment by ferret8888** [comment]
是的，sdk开发人员，有没有做过测试？引入了那么多无用的包，导致各种冲突，服务。sdk开发人员可以与我联系一下 1537863385@qq.com

**Comment by antopen** [comment]
感谢反馈，我们环境中测试没有遇到过这种问题，我加你QQ了解下更多信息。

**Comment by antopen** [comment]
1.1.2版本已添加多平台支持，修复此问题。
