### ISSUE TITLE
Factory.Payment.App().pay()是没经过网络请求吗

### ISSUE THREAD

**Issue by RickoNoNo3** [alipay/alipay-easysdk#268]
这个`Factory.Payment.App().pay()`方法返回的响应对象`payment.app.models.AlipayTradeAppPayResponse`里面只有个body, 其他根本啥也没有, 和[App支付接口2.0](https://opendocs.alipay.com/apis/api_1/alipay.trade.app.pay)里写的开单方法对不上.

检查maven库源码发现这个方法好像就没经过网络请求, 直接封了一套queryString给返回回来了. 这和文档对不上真的可以吗? 我可以就这么拿去用吗?

**Comment by RickoNoNo3** [comment]
#231 有同样问题

**Comment by antopen** [comment]
APP支付服务端只负责将订单信息加签生成一个字符串，不需要有网络请求。
然后再结合APP端上SDK，配合完成APP上支付宝收银台的拉取。
详细流程参见
https://opendocs.alipay.com/open/204/01dcc0
