### ISSUE TITLE
okhttp3.Response 没有close导致内存泄漏

### ISSUE THREAD

**Issue by stevendone** [alipay/alipay-easysdk#269]
警告: A connection to https://openapi.alipay.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by antopen** [comment]
收到，感谢反馈，我们排查是因为引用的okhttp库过老导致的，okhttp最新版本中已经修复了此问题，但由于需要考虑到JDK向下兼容性，不能简单直接升级到最新版本，预计8月底修复发布新版本。

**Comment by stevendone** [comment]
新版的okhttp一样要主动close

Invokes the request immediately, and blocks until the response can be processed or is in error.
To avoid leaking resources callers should close the Response which in turn will close the underlying ResponseBody.
// ensure the response (and underlying response body) is closed
try (Response response = client.newCall(request).execute()) {
  ...
}
