### ISSUE TITLE
部分退款 refund(outTradeNo: string, refundAmount: string)

### ISSUE THREAD

**Issue by daai** [alipay/alipay-easysdk#27]
此接口是否支持部分退款？

**Comment by antopen** [comment]
此接口不支持，实现部分退款需要设置out_request_no这个可选参数，该参数在EasySDK的refund api中不直接支持，可以用Factory.Util.Generic.execute通用接口完成调用，通用接口中可以自行设置所有参数。

实现部分退款参见：
https://opensupport.alipay.com/support/knowledge/27585/201602050896?ant_source=zsearch
