### ISSUE TITLE
.net 5 下PreCreate报错

### ISSUE THREAD

**Issue by KevinWG** [alipay/alipay-easysdk#272]
报错结果如图
开发工具：VS2019
.Net版本：.Net 5.0
方法：Factory.Payment.FaceToFace().PreCreate()
证书模式和公钥模式都会出现

![微信图片_20210805172110](https://user-images.githubusercontent.com/4044201/128327323-db5778be-b5c3-4d77-b024-c14bb3c92003.png)
![微信图片_20210805172416](https://user-images.githubusercontent.com/4044201/128327334-64ed8d65-559c-4f6e-8456-201c56e1ddfd.png)

**Comment by KevinWG** [comment]
相同的证书等信息，使用AlipaySDKNet.Standard 调用成功

**Comment by antopen** [comment]
如果是netcore框架，而不是netframework的话，只能用AlipaySDKNet.Standard，这个才适用于netcore框架
