### ISSUE TITLE
http client过于耦合，不利于异步或者协程的实现

### ISSUE THREAD

**Issue by nsnake** [alipay/alipay-easysdk#28]
HTTP的客户端使用的GuzzleHttp了。而GuzzleHttp本身其实是很开放可以使用协程的方式实现http请求。
目前SDK不支持GuzzleHttp的实现方式。建议把http client的模块解耦做成interface的形式。方便二次开发使用

**Comment by antopen** [comment]
感谢反馈，后续版本中我们考虑下这类问题。
