### ISSUE TITLE
收到，感谢反馈，我们排查是因为引用的okhttp库过老导致的，okhttp最新版本中已经修复了此问题，但由于需要考虑到JDK向下兼容性，不能简单直接升级到最新版本，预计8月底修复发布新版本。

### ISSUE THREAD

**Issue by stevendone** [alipay/alipay-easysdk#280]
收到，感谢反馈，我们排查是因为引用的okhttp库过老导致的，okhttp最新版本中已经修复了此问题，但由于需要考虑到JDK向下兼容性，不能简单直接升级到最新版本，预计8月底修复发布新版本。

_Originally posted by @antopen in https://github.com/alipay/alipay-easysdk/issues/269#issuecomment-894753242_

**Comment by stevendone** [comment]
说好的8月底呢

**Comment by antopen** [comment]
您好，已于今天发布的2.2.1版本中修复此问题。

**Comment by stevendone** [comment]
依赖的easysdk-kernel 1.0.11没有呢，你可以编译吗？你们不测试的吗？这么粗糙的吗？
