### ISSUE TITLE
multiple_bindings with slf4j

### ISSUE THREAD

**Issue by fengzhimengna** [alipay/alipay-easysdk#3]
When run a springboot application, the error occurred bellow:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/E:/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/E:/repository/com/alipay/sdk/alipay-easysdk/1.0.1/alipay-easysdk-1.0.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

what should i do?

**Comment by antopen** [comment]
Thanks for feedback.
We have fixed this warning in version 1.0.2. You can upgrade to this version and try again
