### ISSUE TITLE
可以在每个支付地方单独配置异步通知地址吗?

### ISSUE THREAD

**Issue by ChenZhenJie29770** [alipay/alipay-easysdk#35]
Factory.Payment.Common().create("Iphone6 16G", "202003019443", "0.10", "2088002656718920");
感觉这个不能独立配置异步通知地址不太方便,有多个地方支付也只能一个地址

**Comment by antopen** [comment]
可以使用通用接口
Factory.Util.Generic.execute

这里可以设置任意参数，接口调用中设置的notify_url会自动覆盖config中配置的全局notify_url
