### ISSUE TITLE
退款请求无法提交out_request_id参数

### ISSUE THREAD

**Issue by yixblog** [alipay/alipay-easysdk#37]
根据API文档，部分退款时out_request_id必填。只能换标准sdk了吗

**Comment by Yabandpay** [comment]
您好，麻烦请加微信联系
微信号：n5893111

谢谢


info@yabandmedia.com
 
发件人： Yixian
发送时间： 2020-05-04 17:12
收件人： alipay/alipay-easysdk
抄送： Subscribed
主题： [alipay/alipay-easysdk] 退款请求无法提交out_request_id参数 (#37)
根据API文档，部分退款时out_request_id必填。只能换标准sdk了吗

**Comment by antopen** [comment]
是的，easysdk API暂不直接支持部分退款。 或者用easysdk的通用方法（Factory.Util.Generic.execute），支持自行设置所有可选参数。
