### ISSUE TITLE
所有的Response能不能增加一个统一的属性/方法判断是否成功

### ISSUE THREAD

**Issue by gundamff** [alipay/alipay-easysdk#38]
旧版的api里面有isSuccess(),新版里面只能自己去判断subCode了

**Comment by antopen** [comment]
由于EasySDK的模型对象是通过Tea DSL自动生成的，暂不支持在模型中添加成员方法。
在Tea DSL支持这个特性之前，我们会考虑提供一个AlipayUtils.isSucces(response)辅助方法协助用户判断。
