### ISSUE TITLE
支付create造成未知异常造成无法排错

### ISSUE THREAD

**Issue by daowojia** [alipay/alipay-easysdk#40]
"message": "",
		"file": "../vendor/alipaysdk/easysdk/php/src/Payment/Common/Client.php",
		"code": 0,
		"line": 109,

此文件 109

109> `throw new TeaError([
                    "message" => "验签失败，请检查支付宝公钥设置是否正确。"
                ]);`

**Comment by antopen** [comment]
验签失败，请检查支付宝公钥是否设置正确。
如有疑问可以加入钉钉群中咨询。
