### ISSUE TITLE
境外支付

### ISSUE THREAD

**Issue by Yang-XL** [alipay/alipay-easysdk#44]
此SDK 支持境外支付包 验签吗？

**Comment by Yang-XL** [comment]
netcore 版本

**Comment by antopen** [comment]
针对国际业务的特殊性，支付宝有专门的团队支持，请发送邮件至国际技术保障邮箱（overseas_support@service.alibaba.com） 进行咨询。

这里是国际开放平台地址链接：https://global.alipay.com/，您可以参考一下，关于技术问题，您可以通过海外技术支持邮箱：overseas_support@service.alibaba.com进行咨询；关于业务问题，您也可以通过海外业务服务邮箱：global.service@alipay.com进行咨询
