### ISSUE TITLE
API接口参数灵活性问题

### ISSUE THREAD

**Issue by 1107115073** [alipay/alipay-easysdk#46]
这是原来的API参数：
```
Factory.Payment.Common().create(subject, outTradeNo, totalAmount, buyerId)
```
在使用此API时，需要灵活控制订单支付：
```
// 订单超时
timeout_express

// 异步通知
notify_url
```
此时些API并没有这个参数可选，我应该怎么样扩展呢。
或者说该API的参数是固定的，无法扩展，那么个人觉得不应该牺牲灵活参数而带来便捷。

**Comment by antopen** [comment]
目前想要追求最灵活的参数设置，可以使用通用接口，https://github.com/alipay/alipay-easysdk/blob/master/APIDoc.md#generic。

后续我们也会计划推出可选参数的装配方法。

**Comment by WeihanLi** [comment]
期待更好用的 API
