### ISSUE TITLE
希望增加一个过期时间的配置

### ISSUE THREAD

**Issue by lemos1235** [alipay/alipay-easysdk#49]
默认是90分钟，最好可以自定义。
![image](https://user-images.githubusercontent.com/23135552/82026573-7ee6cc80-96c5-11ea-9768-bf11d5d233f3.png)

**Comment by antopen** [comment]
感谢反馈，后续我们会考虑在Easy API中增加此参数。同时增加可选参数的灵活选配功能。
现阶段如果确实想要设置此参数，请使用Alipay SDK。

**Comment by WeihanLi** [comment]
有计划大概多久可以用吗
