### ISSUE TITLE
希望能尽快修复会员能力中身份认证开始认证接口的问题

### ISSUE THREAD

**Issue by alexzy228** [alipay/alipay-easysdk#50]
会员能力中 身份认证开始认证接口中获取到的 url 链接 打开 签名有问题，希望能尽快修复

**Comment by antopen** [comment]
请问你是用的什么语言的SDK？

**Comment by alexzy228** [comment]
> 请问你是用的什么语言的SDK？

PHP 的 SDK。_generatePage() 的方法使用POST 生成的FORM 表单是正常的，GET生成的链接 签名中的 + 被转为了 空格

**Comment by antopen** [comment]
+号应该是被编码成%2b才对。
你方便加下我们的钉钉群吗，群里我们让同学直接跟您对接下。

**Comment by alexzy228** [comment]
> +号应该是被编码成%2b才对。
> 你方便加下我们的钉钉群吗，群里我们让同学直接跟您对接下。

好的 已经加群了
