### ISSUE TITLE
打算先在本地安装扩展，但是一直安装不上。我试过更新phpunit，但会提示需要更多的依赖，成了个无底洞。我用的PHP版本是7.2.1，laravel版本是5.5，期待回复

### ISSUE THREAD

**Issue by nobodylikeyou** [alipay/alipay-easysdk#51]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for alipaysdk/easysdk 1.2 -> satisfiable by alipaysdk/easysdk[1.2.0].
    - alipaysdk/easysdk 1.2.0 requires phpunit/phpunit ^7.5 -> satisfiable by phpunit/phpunit[7.5.0, 7.5.1, 7.5.10, 7.5.11, 7.5.12, 7.5.13, 7.5.14, 7.5.15, 7.5.16,
 7.5.17, 7.5.18, 7.5.19, 7.5.2, 7.5.20, 7.5.3, 7.5.4, 7.5.5, 7.5.6, 7.5.7, 7.5.8, 7.5.9] but these conflict with your requirements or minimum-stability.

**Comment by sunjim** [comment]
composer remove phpunit/phpunit
composer require alipaysdk/easysdk:^1.2

**Comment by antopen** [comment]
2.0版本已经去除phpunit默认安装
