### ISSUE TITLE
payment.wap.pay返回的应该是actionurl而不是form表单

### ISSUE THREAD

**Issue by zsxfbj** [alipay/alipay-easysdk#52]
之前没升级支付宝证书之前，都是拼接url然后get方式，让用户的浏览器访问网关并唤起支付。

**Comment by antopen** [comment]
手机网站支付一直反馈的是form表单，你说的返回url是看的哪个文档，我们去确认下。

**Comment by zsxfbj** [comment]
我的意思是，我需要get方式请求wap支付，现在sdk封装的只能是post方式的，这时候返回的一个form表单加上一个javascript脚本

**Comment by andysd** [comment]
> 我的意思是，我需要get方式请求wap支付，现在sdk封装的只能是post方式的，这时候返回的一个form表单加上一个javascript脚本

请问你这个问题解决了吗？我这边也是只需要一个url，而不是一个form表单。
以前网页中是这样写的：location.href=https://mapi.alipay.com/gateway.do?xxxxxx
现在用新的sdk不清楚要怎么处理了

**Comment by wzhih** [comment]
返回的表单源码里面，就有你们想要的`url`，通过正则或者字符串查找获取出来就好

**Comment by andysd** [comment]
> 返回的表单源码里面，就有你们想要的`url`，通过正则或者字符串查找获取出来就好
这里我先贴一下返回的body的内容：
```
<form name="punchout_form" method="post" action="https://openapi.alipay.com/gateway.do?alipay_sdk=alipay-easysdk-java-2.0.0&app_id=x.....省略部分内容......&version=1.0">
<input type="hidden" name="biz_content" value="{&quot;out_trade_no&quot;:&quot;202020202020202&quot;,&quot;total_amount&quot;:&quot;0.01&quot;,&quot;subject&quot;:&quot;测试订单名称&quot;,&quot;product_code&quot;:&quot;FAST_INSTANT_TRADE_PAY&quot;}">
<input type="submit" value="立即支付" style="display:none" >
</form>
<script>document.forms[0].submit();</script>
```
返回的源代码中的form表单中有`action`,但是这个action中没有包含业务参数，业务参数而是在name为`biz_content`的隐藏输入框中。

以前的做法是通过get的方式直接访问一个url即可完整支付宝的跳转，因为所有的参数都在url中都有，新版本不兼容这种模式的用法，因为是前后端分离，直接返回一个form表单，前端处理起来很不方便的，不知道这次我描述清楚没有？

**Comment by wzhih** [comment]
> > 返回的表单源码里面，就有你们想要的`url`，通过正则或者字符串查找获取出来就好
> > 这里我先贴一下返回的body的内容：
> 
> ```
> <form name="punchout_form" method="post" action="https://openapi.alipay.com/gateway.do?alipay_sdk=alipay-easysdk-java-2.0.0&app_id=x.....省略部分内容......&version=1.0">
> <input type="hidden" name="biz_content" value="{&quot;out_trade_no&quot;:&quot;202020202020202&quot;,&quot;total_amount&quot;:&quot;0.01&quot;,&quot;subject&quot;:&quot;测试订单名称&quot;,&quot;product_code&quot;:&quot;FAST_INSTANT_TRADE_PAY&quot;}">
> <input type="submit" value="立即支付" style="display:none" >
> </form>
> <script>document.forms[0].submit();</script>
> ```
> 
> 返回的源代码中的form表单中有`action`,但是这个action中没有包含业务参数，业务参数而是在name为`biz_content`的隐藏输入框中。
> 
> 以前的做法是通过get的方式直接访问一个url即可完整支付宝的跳转，因为所有的参数都在url中都有，新版本不兼容这种模式的用法，因为是前后端分离，直接返回一个form表单，前端处理起来很不方便的，不知道这次我描述清楚没有？

把`action`提取出来，再把表单项附加到`action`这个`url`后面，通过`GET`形式附加参数，然后把这个`url`给前端就好

如果想自己做提交，可以后端`POST`过去，会返回`302`重定向的链接，把这个链接给前端也行

**Comment by tohodog** [comment]
看源码里有支持GET的方式,但是写死了,我重写了一个类

**Comment by OverNaive** [comment]
`Factory::payment()->wap()->pay()`
`Factory::payment()->page()->pay()`

建议在以上接口返回的对象中，新增一个字段，返回 GET 方式的 URL。

例如：

```
$response = [
    "body" => $this->_kernel->generatePage("POST", $systemParams, $bizParams, $textParams, $sign)
];
```
新增 URL 字段
```
$response = [
    "url" => $this->_kernel->generatePage("GET", $systemParams, $bizParams, $textParams, $sign),
    "body" => $this->_kernel->generatePage("POST", $systemParams, $bizParams, $textParams, $sign)
];
```

这样开发者就能自由选择了。

感恩开源！

**Comment by antopen** [comment]
感谢反馈，下个版本会考虑加入GET模式的方法。
