### ISSUE TITLE
Util-Generic-execute 方法调用问题

### ISSUE THREAD

**Issue by daai** [alipay/alipay-easysdk#53]
alipay.fund.trans.uni.transfer  单笔转账总是提示 产品未签约 ，实际是签约了，而且使用alipay-sdk-java 完全能转账。实在无语了。
Factory.Util.Generic().execute("alipay.fund.trans.uni.transfer", null, map);

**Comment by antopen** [comment]
如果确认账号都是用的同一个的话，这种情况一般是由于map里面的参数设置有误，比如部分参数的字段key值设置的不一致。你可以加钉钉群，里面反馈更多上下文，我们帮你看看。
