### ISSUE TITLE
wap支付异步回调参数验证失败

### ISSUE THREAD

**Issue by xywf221** [alipay/alipay-easysdk#58]
如题排查发现参数中的 fund_bill_list 的值为 ```[{&quot;amount&quot;:&quot;0.01&quot;,&quot;fundChannel&quot;:&quot;PCREDIT&quot;}]``` 使用 html_entity_decode 函数解码后 验证成功！

**Comment by luoyan520** [comment]
这个问题我也遇到过，经排查是框架的问题，我所使用的是ThinkPHP6.0。你遇到的情况应该也是类似，我是直接通过str_replace(&quot, '"', $data)解决的
