### ISSUE TITLE
Spring Boot stuck at startup after adding alipay-easysdk

### ISSUE THREAD

**Issue by parorisim** [alipay/alipay-easysdk#6]
I'm using Spring Boot 2.2.5.RELEASE with Kotlin 1.3.70. After adding alipay-easysdk, the application just stuck at startup and no error log printed but behaves normally without this sdk.

**Comment by parorisim** [comment]
After some digging, I realized that my application runs well but just without log info output. Easysdk overwritten my log config. How can I fix it?

**Comment by antopen** [comment]
Which version do you use？

**Comment by parorisim** [comment]
@antopen 1.1.1

**Comment by antopen** [comment]
Alipay Easy SDK does have a default logback config file built in，you can try to put a logback.xml configuration file in your project resources folder to overwrite it。


----------------------  default logback config file content  is as follows ---------------------- 
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
    <property name="LOG_DIR" value="logs"/>
    <property name="pattern" value="%d{yyyyMMdd:HH:mm:ss.SSS} [%thread] %-5level  %msg%n"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <target>System.out</target>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>${pattern}</pattern>
        </encoder>
    </appender>

    <appender name="DEFAULT_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${LOG_DIR}/default.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>${LOG_DIR}/default_%d{yyyy-MM-dd}.log.%i.gz</fileNamePattern>
            <maxFileSize>20MB</maxFileSize>
            <maxHistory>15</maxHistory>
        </rollingPolicy>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>${pattern}</pattern>
        </encoder>
    </appender>

    <appender name="ERROR_FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${LOG_DIR}/common-error.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>${LOG_DIR}/common-error_%d{yyyy-MM-dd}.log.%i.gz</fileNamePattern>
            <maxFileSize>20MB</maxFileSize>
            <maxHistory>15</maxHistory>
        </rollingPolicy>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>${pattern}</pattern>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>ERROR</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
    </appender>

    <root level="INFO">
        <appender-ref ref="DEFAULT_FILE"/>
        <appender-ref ref="ERROR_FILE"/>
    </root>
</configuration>

**Comment by xiaofangs** [comment]
![0XNCV_SG(DS~%FH4Y92ELRS](https://user-images.githubusercontent.com/46215469/77143502-6a6bc680-6abe-11ea-87a7-85b2025daf20.png)
![RA6TJ4QX2M D@NBH5~V((FI](https://user-images.githubusercontent.com/46215469/77143523-75bef200-6abe-11ea-862e-869b1c9615d3.png)
