### ISSUE TITLE
PHP alipay.merchant.item.file.upload 这个接口无法使用

### ISSUE THREAD

**Issue by srcker** [alipay/alipay-easysdk#63]
接口`alipay.merchant.item.file.upload`
使用 `execute` 方法不能使用 header不同

**Comment by antopen** [comment]
文件上传类接口无法使用通用的execute方法。
这个我们尽快针对alipay.merchant.item.file.upload提供专用的API。

**Comment by antopen** [comment]
可以通过Util-》Generic-》fileExecute 通用接口调用
