### ISSUE TITLE
有些方法调用toMap()报错

### ISSUE THREAD

**Issue by noobzhp** [alipay/alipay-easysdk#65]
faceToFace()->pay()->toMap();
common()->query()->toMap();这个接口在支付成功以后调用会报错
报错信息：Call to a member function toMap() on array
alipaysdk\easysdk\php\src\Payment\Common\Models\AlipayTradeQueryResponse.php:126
if(null !== $this->fundBillList && is_array($this->fundBillList)){

            $n = 0;

            foreach($this->fundBillList as $item){

                $res['fund_bill_list'][$n++] = null !== $item ? $item->toMap() : $item;

            }

        }

是我调用的问题吗？

**Comment by antopen** [comment]
建议加入钉钉群提供更多上下文，以便定位。
