### ISSUE TITLE
证书读取方式

### ISSUE THREAD

**Issue by licheng1013** [alipay/alipay-easysdk#66]
//构造client 
CertAlipayRequest certAlipayRequest = new CertAlipayRequest();
//设置应用公钥证书路径
certAlipayRequest.setCertPath(app_cert_path);
//设置支付宝公钥证书路径
certAlipayRequest.setAlipayPublicCertPath(alipay_cert_path);
//设置支付宝根证书路径
certAlipayRequest.setRootCertPath(alipay_root_cert_path);

//能不能传个文件流进去

**Comment by zp253908058** [comment]
https://github.com/alipay/alipay-easysdk/issues/33

**Comment by antopen** [comment]
感谢反馈，目前暂时不能，下个版本规划中，我们已加入直接以String的形式设置证书内容的功能。
