### ISSUE TITLE
composer 安装报错，提示phpunit/phpunit 要7.5 但是我的phpunit/phpunit是8.5的

### ISSUE THREAD

**Issue by cnjackven** [alipay/alipay-easysdk#68]
composer 安装报错，提示phpunit/phpunit 要7.5 但是我的phpunit/phpunit是8.5的，更高版本不支持，非要降低版本吗？

**Comment by aiwozhe** [comment]
希望作者升级下或做下兼容，同样遇到了

**Comment by l333308** [comment]
laravel6.X phpunit:8.5 同样遇到此问题

**Comment by antopen** [comment]
下个版本我们做下兼容，现在安装冲突可以先 --ignore-platform-reqs 忽略版本问题

**Comment by antopen** [comment]
2.0版本已经去除默认安装phpunit
