### ISSUE TITLE
Java  订单关闭 不行

### ISSUE THREAD

**Issue by zuoni1018** [alipay/alipay-easysdk#75]
{
    "httpBody":"{"alipay_trade_close_response":{"code":"40004","msg":"Business Failed","sub_code":"ACQ.TRADE_STATUS_ERROR","sub_msg":"交易状态不合法","out_trade_no":"100109"},"sign":"CZSTC9KpFxL6/3Ixu8Nkv/sC7bNhUTtZ8/Ew7leO+PIee8HbF32Blx9rLQ6AAiXSGFhhyMtXMz9SK8u9fjXWf1ms7QF6QlyPnSqitGgtJ/82ys/DhKQ1YJs40Yoi+glIeGCCV264yNC1wQatKUMURxzTs3L2a0e8js0IjbNNQhhc5eEuntZ+W+X5bRp6A3K4naLj69vh8W9pXw+5w8MEpc+N0LcrKzWYs/ARlwPIL5L/dCoyw3yYeb+xc/w+EcYQ+iWO8hMxkAJf0tX6YgpZftIi9Rt1NyUGRmNG+QtLQb14oxptZSoIna/qBUr97VmhLPc30DTHkJOEJPFiSGL8jg=="}",
    "code":"40004",
    "msg":"Business Failed",
    "subCode":"ACQ.TRADE_STATUS_ERROR",
    "subMsg":"交易状态不合法",
    "outTradeNo":"100109"
}

**Comment by antopen** [comment]
这是业务逻辑问题，您可以去钉钉群 - 小程序支付宝技术支持群，群号：23319593
中进行进一步咨询。
