### ISSUE TITLE
请问预授权冻结调用哪一个接口?

### ISSUE THREAD

**Issue by hhniao** [alipay/alipay-easysdk#76]
没有看到预授权冻结的调用接口.
如何扩展这个sdk?

**Comment by antopen** [comment]
使用Factory.Util.Generic.execute通用接口可以扩展调用绝大部分OpenAPI。（具体说明参加APIDoc文档）。

**Comment by hhniao** [comment]
@antopen 看到有execute方法, 但是没有找到 sdkExecute方法.
我这边需要服务端生成参数, 让客户端, 执行支付操作.

**Comment by antopen** [comment]
不好意思，之前没注意到这个接口的特殊性。

sdkExecute目前alipayeasysdk暂时没有提供替换的方法，这个我们后续尽快加上。

**Comment by ezhiyu126** [comment]
我遇到了这个问题无法在目前的sdk 使用sdkExecute 使用execute方法一直报系统繁忙
