### ISSUE TITLE
请教！有证书时，PC支付回调，如何验签啊？

### ISSUE THREAD

**Issue by Kanguruo** [alipay/alipay-easysdk#79]

**Comment by Kanguruo** [comment]
找到一个extractAlipayPublicKey需要参数alipayCertSN，然后getAlipayCertSN需要一个respMap，然后。。。。。。

**Comment by antopen** [comment]
Factory.setOptions设置好证书后，调用Payment.Common().veriftyNotify接口就可以了。不需要再自己去从证书中提取公钥。
