### ISSUE TITLE
网页提示：抱歉，网络系统繁忙，请稍后再试。

### ISSUE THREAD

**Issue by nkw1996** [alipay/alipay-easysdk#80]
沙箱环境：调用网站支付 ，点击付款后提示 ：抱歉，网络系统繁忙，请稍后再试。（未收到同步通知，查看沙箱账户金额，已完成变动）多次测试都出现该问题

**Comment by cn-yh** [comment]
可能当时是沙箱在进行环境维护，现在再试试。
![image](https://user-images.githubusercontent.com/13514669/87371476-0ebad100-c5b8-11ea-932a-3f1fcd4d522e.png)
