### ISSUE TITLE
Factory.Payment.App().pay返回的timestamp格式不正确

### ISSUE THREAD

**Issue by BruceAn1978** [alipay/alipay-easysdk#81]
调用Factory.Payment.App().pay()方式预下单后，返回的信息中timestamp参数值为“2020-07-02+09%3A24%3A38”格式的，直接呼起App端支付SDK的时候报timestamp格式不正确。

按照文档修改timestamp格式后，又会引起签名不正确的问题（签名又是按照上面的日期格式做的）。

**Comment by antopen** [comment]
返回的字符串会进行urlencode，所以timestamp的值是2020-07-02+09%3A24%3A38，这个格式是正确的。
推荐前往https://opensupport.alipay.com/support/home.htm联系技术支持，排查其他原因。
