### ISSUE TITLE
Call to undefined method Alipay\EasySDK\Kernel\EasySDKKernel::verifyParams()

### ISSUE THREAD

**Issue by mryun11** [alipay/alipay-easysdk#86]
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/12914415/86702714-ccd4dc80-c045-11ea-87d0-de9358fedfec.png">

**Comment by m13535921099** [comment]
在`KernelEasySDKKernel.php` 文件中新增`verifyParams`方法

文件路径：alipaysdk\easysdk\php\src\KernelEasySDKKernel.php

方法：
`public function verifyParams($parameters, $publicKey)
{
    $signer = new Signer();
    return $signer->verifyParams($parameters, $publicKey);
}`

**Comment by antopen** [comment]
请使用2.0.1版本
