### ISSUE TITLE
支付宝沙箱

### ISSUE THREAD

**Issue by wanglong1996** [alipay/alipay-easysdk#90]
支持沙箱调试吗

**Comment by cn-yh** [comment]
支持的，gatewayHost 配置成沙箱的网关地址：openapi.alipaydev.com，
appId，merchantPrivateKey，alipayPublicKey也配置成沙箱对应的配置就行了。
![image](https://user-images.githubusercontent.com/13514669/87133936-99ef4a80-c2ca-11ea-90e6-cf10cbddd9c8.png)
