### ISSUE TITLE
Factory.Payment.FaceToFace调用成功但是Factory.Payment.Page().Pay提示签名错误

### ISSUE THREAD

**Issue by hellofengge** [alipay/alipay-easysdk#93]
我使用的相同配置调用SDK时Factory.Payment.FaceToFace返回了调用成功，但是访问Factory.Payment.Page().Pay返回的body里的action的url时提示签名错误，请问是我使用方法有问题吗?

**Comment by 1471817541** [comment]
看下是不是私钥不对,或者在运行过程中私钥 丢失精度了,我也遇到了这个情况
