### ISSUE TITLE
Factory.Payment.Page().Pay，如果Subject里含有某些汉字会导致签名错误

### ISSUE THREAD

**Issue by winfredxu** [alipay/alipay-easysdk#95]
使用环境：PC网页支付
SDK: .net 版本

如果Subject里面含有“版”字，则签名错误
![1594718864(1)](https://user-images.githubusercontent.com/13715502/87409591-b99eaf80-c5f7-11ea-8019-0f769dd37bee.jpg)

![1594718826](https://user-images.githubusercontent.com/13715502/87409633-cb805280-c5f7-11ea-9bc7-36b9e6b8e3d2.png)

不包含版字，没有问题。

**Comment by winfredxu** [comment]
含有特殊字符，例如“—”也会抛同样错误

**Comment by hellofengge** [comment]
我的商品名含有“板” 难道是因为这个原因吗？

**Comment by winfredxu** [comment]
> 我的商品名含有“板” 难道是因为这个原因吗？

你可以换成英文的商品名试试看。。。

**Comment by winfredxu** [comment]
Content(response.Body, "text/html", Encoding.UTF8);

需要设置下Response的Charset....关闭。。
