### ISSUE TITLE
请问一下目前是否有dotnet支付回调处理的Sample

### ISSUE THREAD

**Issue by wanglantian** [alipay/alipay-easysdk#96]
感觉sdk里面应该对回调做了处理，只是不知道怎么使用，请教一下

**Comment by WeihanLi** [comment]
sdk 里的回调只是帮你验证一下签名，具体逻辑还是要自己实现，使用示例如下：

``` csharp
var signatureValid = Factory.Payment.Common() .VerifyNotify(paramsCollection);
```

**Comment by wanglantian** [comment]
> sdk 里的回调只是帮你验证一下签名，具体逻辑还是要自己实现，使用示例如下：
> 
> ```cs
> // paramsCollection 是回调请求参数转成的字典
> var signatureValid = Factory.Payment.Common() .VerifyNotify(paramsCollection);
> ```

了解了,多谢解答
